// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jC2U9K1N9JvhseSFlKT5AtTA37WlZIM',
    appId: '1:1011646736895:web:c60a9a7f7f88fe10f91fca',
    messagingSenderId: '1011646736895',
    projectId: 'uniclub-7b35b',
    authDomain: 'uniclub-7b35b.firebaseapp.com',
    storageBucket: 'uniclub-7b35b.firebasestorage.app',
    measurementId: 'G-390S4GV9VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl41Dn7ak9-npDGKgUXHS4SGAkLfjDS0I',
    appId: '1:1011646736895:android:838536ad6d75f77bf91fca',
    messagingSenderId: '1011646736895',
    projectId: 'uniclub-7b35b',
    storageBucket: 'uniclub-7b35b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdFsM5ENEcwes90qmvV4sIFYAQ79y07I',
    appId: '1:1011646736895:ios:da858b5d7d1fe3aaf91fca',
    messagingSenderId: '1011646736895',
    projectId: 'uniclub-7b35b',
    storageBucket: 'uniclub-7b35b.firebasestorage.app',
    iosBundleId: 'com.example.uniclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdFsM5ENEcwes90qmvV4sIFYAQ79y07I',
    appId: '1:1011646736895:ios:da858b5d7d1fe3aaf91fca',
    messagingSenderId: '1011646736895',
    projectId: 'uniclub-7b35b',
    storageBucket: 'uniclub-7b35b.firebasestorage.app',
    iosBundleId: 'com.example.uniclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jC2U9K1N9JvhseSFlKT5AtTA37WlZIM',
    appId: '1:1011646736895:web:de0af2ad15259e38f91fca',
    messagingSenderId: '1011646736895',
    projectId: 'uniclub-7b35b',
    authDomain: 'uniclub-7b35b.firebaseapp.com',
    storageBucket: 'uniclub-7b35b.firebasestorage.app',
    measurementId: 'G-0B50PLDSPV',
  );
}
